Submodules updated

diff --git a/azure/posix.yml b/azure/posix.yml
--- a/azure/posix.yml
+++ b/azure/posix.yml
@@ -36,6 +36,13 @@ jobs:
 
       - bash: |
           set -e
+          uname -m
+          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+        condition: eq(variables['PLAT'], 'aarch64')
+        displayName: Setting up QEMU to run aarch64 images.
+
+      - bash: |
+          set -e
 
           if [ "$BUILD_REASON" == "Schedule" ]; then
             BUILD_COMMIT=$NIGHTLY_BUILD_COMMIT
@@ -49,6 +56,18 @@ jobs:
             echo "##vso[task.setvariable variable=MACOSX_DEPLOYMENT_TARGET]10.9"
           else
             echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
+          fi
+
+          if [ `uname` != 'Darwin' ]; then
+            if [[ "$PLAT" == x86_64 ]]; then
+                ARCH="amd64"
+            elif [[ "$PLAT" == aarch64 ]]; then
+                ARCH="arm64"
+            else
+                echo "Invalid platform = '"$PLAT"'. Supported values are  'x86_64', 'aarch64'"
+                exit 1
+            fi
+            echo "##vso[task.setvariable variable=ARCH]$ARCH"
           fi
 
           # Store original Python path to be able to create test_venv pointing
